/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PICT;

import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Ajinkya
 */
public final class AdminDashBord extends javax.swing.JFrame
{   int second,minute,hour;
   
    /**
     * Creates new form MainWindow
     */
    
    @Override 
    public void setResizable(boolean resizable) 
    {
        super.setResizable(resizable); //To change body of generated methods, choose Tools | Templates.
      
       
    }

    public AdminDashBord() {
        setResizable(false);
        initComponents();
        ImageIcon img1 = new ImageIcon("src//img//busicon.PNG");
        this.setIconImage(img1.getImage());
          DigitalClock digitalClock = new DigitalClock();
        timepane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        timepane.add(digitalClock);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnadmin2 = new javax.swing.JButton();
        btnemploye2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnemploye4 = new javax.swing.JButton();
        btnadmin3 = new javax.swing.JButton();
        btnadmin7 = new javax.swing.JButton();
        btnemploye6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pane = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnemploye7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnadmin8 = new javax.swing.JButton();
        btnemploye = new javax.swing.JButton();
        timepane = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bus Ticket Reservation System");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(100, 100, 0, 0));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnadmin2.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnadmin2.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin2.setText("View/Update");
        btnadmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin2ActionPerformed(evt);
            }
        });

        btnemploye2.setBackground(new java.awt.Color(0, 0, 0));
        btnemploye2.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnemploye2.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye2.setText("Add");
        btnemploye2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemploye2ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busicon.png"))); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Buses");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/routeicon.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Route");

        btnemploye4.setBackground(new java.awt.Color(0, 0, 0));
        btnemploye4.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnemploye4.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye4.setText("Add");
        btnemploye4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemploye4ActionPerformed(evt);
            }
        });

        btnadmin3.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin3.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnadmin3.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin3.setText("View/Update");
        btnadmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin3ActionPerformed(evt);
            }
        });

        btnadmin7.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin7.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnadmin7.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin7.setText("View/Update");
        btnadmin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin7ActionPerformed(evt);
            }
        });

        btnemploye6.setBackground(new java.awt.Color(0, 0, 0));
        btnemploye6.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnemploye6.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye6.setText("Add");
        btnemploye6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemploye6ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Routinee");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Calendar-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel5))
                    .addComponent(btnemploye2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnemploye4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9))
                    .addComponent(btnemploye6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadmin7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(btnemploye2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnadmin2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(btnemploye4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnadmin3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(btnemploye6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnadmin7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pane.setOpaque(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fbackm.jpg"))); // NOI18N
        pane.add(jLabel2);
        jLabel2.setBounds(0, 0, 1530, 770);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Preppy-icon.png"))); // NOI18N

        btnemploye7.setBackground(new java.awt.Color(0, 0, 0));
        btnemploye7.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnemploye7.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye7.setText("Add");
        btnemploye7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemploye7ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Employee");

        btnadmin8.setBackground(new java.awt.Color(0, 0, 0));
        btnadmin8.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        btnadmin8.setForeground(new java.awt.Color(255, 255, 255));
        btnadmin8.setText("View/Update");
        btnadmin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadmin8ActionPerformed(evt);
            }
        });

        btnemploye.setBackground(new java.awt.Color(255, 51, 51));
        btnemploye.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btnemploye.setForeground(new java.awt.Color(255, 255, 255));
        btnemploye.setText("SignOut");
        btnemploye.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnemploye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemployeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout timepaneLayout = new javax.swing.GroupLayout(timepane);
        timepane.setLayout(timepaneLayout);
        timepaneLayout.setHorizontalGroup(
            timepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        timepaneLayout.setVerticalGroup(
            timepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Administrator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pane)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnadmin8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnemploye7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pane, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadmin8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnemploye7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(timepane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnemploye, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formPropertyChange

    private void btnemploye7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemploye7ActionPerformed

    }//GEN-LAST:event_btnemploye7ActionPerformed

    private void btnadmin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin8ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnadmin8ActionPerformed

    private void btnemploye6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemploye6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnemploye6ActionPerformed

    private void btnadmin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin7ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnadmin7ActionPerformed

    private void btnadmin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnadmin3ActionPerformed

    private void btnemploye4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemploye4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnemploye4ActionPerformed

    private void btnemployeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemployeActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login log=new Login();
        log.setLocation(300,200);
        log.setVisible(true);
    }//GEN-LAST:event_btnemployeActionPerformed

    private void btnemploye2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemploye2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnemploye2ActionPerformed

    private void btnadmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadmin2ActionPerformed
        // TODO add your handling code here:
        ViewBuses vbus=new ViewBuses();
        pane.add(vbus);
        vbus.setLocation(200,5);
        vbus.setVisible(true);
    }//GEN-LAST:event_btnadmin2ActionPerformed

  /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        try {
            // select Look and Feel
            Properties props = new Properties();
  props.put("logoString", "");
  
            TextureLookAndFeel.setCurrentTheme(props);
            UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
            
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
       
              
     new AdminDashBord().setVisible(true);
            
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin2;
    private javax.swing.JButton btnadmin3;
    private javax.swing.JButton btnadmin7;
    private javax.swing.JButton btnadmin8;
    private javax.swing.JButton btnemploye;
    private javax.swing.JButton btnemploye2;
    private javax.swing.JButton btnemploye4;
    private javax.swing.JButton btnemploye6;
    private javax.swing.JButton btnemploye7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JDesktopPane pane;
    private javax.swing.JPanel timepane;
    // End of variables declaration//GEN-END:variables
}
